// Auto-generated by OpenLane
module eth_phy_1g(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input[7:0] eth_data_in,
  input eth_valid_in,
  output[9:0] phy_data_out,
  output phy_valid_out
);
endmodule
